name: "Update wmc dependencies"
description: "Updates wmc npm packages and submodules"
author: "ZukenHammer"

inputs:
  token:
    description: "Token to read the submodules and npm packages"
    required: true
  customScript:
    description: "The custom script will be executed after all dependencies were updated and right before checking in the changes regardless of wether there where any dependencies updates or not"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.customScript }}